In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
a=np.arange(12);
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

## Pandas Library
#### Panal Data System
#### used for data manipulation

In [3]:
a=pd.Series([1,2,3,4])
print(a)
print(type(a))

0    1
1    2
2    3
3    4
dtype: int64
<class 'pandas.core.series.Series'>

In [5]:
a=pd.Series((8,9,7));
print(a);
print((type(a)));

0    8
1    9
2    7
dtype: int64
<class 'pandas.core.series.Series'>

In [7]:
a=pd.Series({
'a':'Python',
'b':'Java'});
print(a);
print(type(a))

a    Python
b      Java
dtype: object
<class 'pandas.core.series.Series'>

In [8]:
pd.Series(range(1,6))

0    1
1    2
2    3
3    4
4    5
dtype: int64

## DataFrame
- A 2D pandas data Structure
- includes rows and columns
- A group of multiple dataframes is called panel

In [10]:
pd.DataFrame({
    'name':['a','B','C'],
    'marks':[80,90,100]
})

  name  marks
0    a     80
1    B     90
2    C    100

In [13]:
# using lists of list
pd.DataFrame([['A',80],['B',90]],columns=['name','marks'])

  name  marks
0    A     80
1    B     90

In [15]:
pd.DataFrame([
    {'name':'A','Marks':100},
    {'name':'b','Marks':10}
])

  name  Marks
0    A    100
1    b     10

## With Csv

In [16]:
df=pd.read_csv("p1.csv")

In [17]:
df

  name  age       city
0    a   15  Ahemdabad
1    b   18      surat
2    c   20     mumbai

In [18]:
df=pd.read_csv("students.csv")
df

    StudentID    Name Department   Age  Marks  Attendance       City
0           1    Amit         CS  20.0   85.0        92.0  Ahmedabad
1           2    Neha         IT  21.0   78.0        88.0      Surat
2           3    Ravi         CS  19.0   90.0        95.0  Ahmedabad
3           4    Sara         EC  22.0   66.0        70.0   Vadodara
4           5    John         IT  20.0  120.0        85.0     Rajkot
5           6   Kiran         CS  21.0   81.0        90.0  Ahmedabad
6           7    Riya         IT  20.0   76.0         NaN      Surat
7           8   Arjun         CS  22.0    NaN        93.0  Ahmedabad
8           9   Pooja         EC  19.0   69.0        75.0   Vadodara
9          10   Mehul         CS  21.0   92.0        97.0  Ahmedabad
10         11   Anita         IT  20.0   74.0        80.0      Surat
11         12   Rohan         CS  22.0   84.0        91.0  Ahmedabad
12         13   Deepa         EC   NaN   67.0        72.0   Vadodara
13         14   Sneha         IT  20.0   79.0        86.0      Surat
14         15   Kunal         CS  23.0   91.0        96.0  Ahmedabad
15         16   Payal         EC  19.0   65.0        68.0   Vadodara
16         17  Nikhil         IT  22.0   83.0        89.0      Surat
17         18  Simran         CS  21.0   87.0        94.0  Ahmedabad
18         19   Tarun         CS  20.0   77.0        84.0     Rajkot
19         20    Isha         IT   NaN   30.0        87.0      Surat
20          2    Neha         IT  21.0   78.0        88.0      Surat
21          6   Kiran         CS  21.0   81.0        90.0  Ahmedabad

In [19]:
df.set_index("StudentID")

             Name Department   Age  Marks  Attendance       City
StudentID
1            Amit         CS  20.0   85.0        92.0  Ahmedabad
2            Neha         IT  21.0   78.0        88.0      Surat
3            Ravi         CS  19.0   90.0        95.0  Ahmedabad
4            Sara         EC  22.0   66.0        70.0   Vadodara
5            John         IT  20.0  120.0        85.0     Rajkot
6           Kiran         CS  21.0   81.0        90.0  Ahmedabad
7            Riya         IT  20.0   76.0         NaN      Surat
8           Arjun         CS  22.0    NaN        93.0  Ahmedabad
9           Pooja         EC  19.0   69.0        75.0   Vadodara
10          Mehul         CS  21.0   92.0        97.0  Ahmedabad
11          Anita         IT  20.0   74.0        80.0      Surat
12          Rohan         CS  22.0   84.0        91.0  Ahmedabad
13          Deepa         EC   NaN   67.0        72.0   Vadodara
14          Sneha         IT  20.0   79.0        86.0      Surat
15          Kunal         CS  23.0   91.0        96.0  Ahmedabad
16          Payal         EC  19.0   65.0        68.0   Vadodara
17         Nikhil         IT  22.0   83.0        89.0      Surat
18         Simran         CS  21.0   87.0        94.0  Ahmedabad
19          Tarun         CS  20.0   77.0        84.0     Rajkot
20           Isha         IT   NaN   30.0        87.0      Surat
2            Neha         IT  21.0   78.0        88.0      Surat
6           Kiran         CS  21.0   81.0        90.0  Ahmedabad

In [20]:
df ##old DataFrame doesn't change by default

    StudentID    Name Department   Age  Marks  Attendance       City
0           1    Amit         CS  20.0   85.0        92.0  Ahmedabad
1           2    Neha         IT  21.0   78.0        88.0      Surat
2           3    Ravi         CS  19.0   90.0        95.0  Ahmedabad
3           4    Sara         EC  22.0   66.0        70.0   Vadodara
4           5    John         IT  20.0  120.0        85.0     Rajkot
5           6   Kiran         CS  21.0   81.0        90.0  Ahmedabad
6           7    Riya         IT  20.0   76.0         NaN      Surat
7           8   Arjun         CS  22.0    NaN        93.0  Ahmedabad
8           9   Pooja         EC  19.0   69.0        75.0   Vadodara
9          10   Mehul         CS  21.0   92.0        97.0  Ahmedabad
10         11   Anita         IT  20.0   74.0        80.0      Surat
11         12   Rohan         CS  22.0   84.0        91.0  Ahmedabad
12         13   Deepa         EC   NaN   67.0        72.0   Vadodara
13         14   Sneha         IT  20.0   79.0        86.0      Surat
14         15   Kunal         CS  23.0   91.0        96.0  Ahmedabad
15         16   Payal         EC  19.0   65.0        68.0   Vadodara
16         17  Nikhil         IT  22.0   83.0        89.0      Surat
17         18  Simran         CS  21.0   87.0        94.0  Ahmedabad
18         19   Tarun         CS  20.0   77.0        84.0     Rajkot
19         20    Isha         IT   NaN   30.0        87.0      Surat
20          2    Neha         IT  21.0   78.0        88.0      Surat
21          6   Kiran         CS  21.0   81.0        90.0  Ahmedabad

In [22]:
df.set_index("StudentID", inplace=True) ## don't run it twice as it checks all the the colums except existing(previous original) index

In [23]:
df

             Name Department   Age  Marks  Attendance       City
StudentID
1            Amit         CS  20.0   85.0        92.0  Ahmedabad
2            Neha         IT  21.0   78.0        88.0      Surat
3            Ravi         CS  19.0   90.0        95.0  Ahmedabad
4            Sara         EC  22.0   66.0        70.0   Vadodara
5            John         IT  20.0  120.0        85.0     Rajkot
6           Kiran         CS  21.0   81.0        90.0  Ahmedabad
7            Riya         IT  20.0   76.0         NaN      Surat
8           Arjun         CS  22.0    NaN        93.0  Ahmedabad
9           Pooja         EC  19.0   69.0        75.0   Vadodara
10          Mehul         CS  21.0   92.0        97.0  Ahmedabad
11          Anita         IT  20.0   74.0        80.0      Surat
12          Rohan         CS  22.0   84.0        91.0  Ahmedabad
13          Deepa         EC   NaN   67.0        72.0   Vadodara
14          Sneha         IT  20.0   79.0        86.0      Surat
15          Kunal         CS  23.0   91.0        96.0  Ahmedabad
16          Payal         EC  19.0   65.0        68.0   Vadodara
17         Nikhil         IT  22.0   83.0        89.0      Surat
18         Simran         CS  21.0   87.0        94.0  Ahmedabad
19          Tarun         CS  20.0   77.0        84.0     Rajkot
20           Isha         IT   NaN   30.0        87.0      Surat
2            Neha         IT  21.0   78.0        88.0      Surat
6           Kiran         CS  21.0   81.0        90.0  Ahmedabad

In [24]:
df.reset_index() ##only one time change/reset

    StudentID    Name Department   Age  Marks  Attendance       City
0           1    Amit         CS  20.0   85.0        92.0  Ahmedabad
1           2    Neha         IT  21.0   78.0        88.0      Surat
2           3    Ravi         CS  19.0   90.0        95.0  Ahmedabad
3           4    Sara         EC  22.0   66.0        70.0   Vadodara
4           5    John         IT  20.0  120.0        85.0     Rajkot
5           6   Kiran         CS  21.0   81.0        90.0  Ahmedabad
6           7    Riya         IT  20.0   76.0         NaN      Surat
7           8   Arjun         CS  22.0    NaN        93.0  Ahmedabad
8           9   Pooja         EC  19.0   69.0        75.0   Vadodara
9          10   Mehul         CS  21.0   92.0        97.0  Ahmedabad
10         11   Anita         IT  20.0   74.0        80.0      Surat
11         12   Rohan         CS  22.0   84.0        91.0  Ahmedabad
12         13   Deepa         EC   NaN   67.0        72.0   Vadodara
13         14   Sneha         IT  20.0   79.0        86.0      Surat
14         15   Kunal         CS  23.0   91.0        96.0  Ahmedabad
15         16   Payal         EC  19.0   65.0        68.0   Vadodara
16         17  Nikhil         IT  22.0   83.0        89.0      Surat
17         18  Simran         CS  21.0   87.0        94.0  Ahmedabad
18         19   Tarun         CS  20.0   77.0        84.0     Rajkot
19         20    Isha         IT   NaN   30.0        87.0      Surat
20          2    Neha         IT  21.0   78.0        88.0      Surat
21          6   Kiran         CS  21.0   81.0        90.0  Ahmedabad

In [25]:
df

             Name Department   Age  Marks  Attendance       City
StudentID
1            Amit         CS  20.0   85.0        92.0  Ahmedabad
2            Neha         IT  21.0   78.0        88.0      Surat
3            Ravi         CS  19.0   90.0        95.0  Ahmedabad
4            Sara         EC  22.0   66.0        70.0   Vadodara
5            John         IT  20.0  120.0        85.0     Rajkot
6           Kiran         CS  21.0   81.0        90.0  Ahmedabad
7            Riya         IT  20.0   76.0         NaN      Surat
8           Arjun         CS  22.0    NaN        93.0  Ahmedabad
9           Pooja         EC  19.0   69.0        75.0   Vadodara
10          Mehul         CS  21.0   92.0        97.0  Ahmedabad
11          Anita         IT  20.0   74.0        80.0      Surat
12          Rohan         CS  22.0   84.0        91.0  Ahmedabad
13          Deepa         EC   NaN   67.0        72.0   Vadodara
14          Sneha         IT  20.0   79.0        86.0      Surat
15          Kunal         CS  23.0   91.0        96.0  Ahmedabad
16          Payal         EC  19.0   65.0        68.0   Vadodara
17         Nikhil         IT  22.0   83.0        89.0      Surat
18         Simran         CS  21.0   87.0        94.0  Ahmedabad
19          Tarun         CS  20.0   77.0        84.0     Rajkot
20           Isha         IT   NaN   30.0        87.0      Surat
2            Neha         IT  21.0   78.0        88.0      Surat
6           Kiran         CS  21.0   81.0        90.0  Ahmedabad

In [26]:
df.reset_index(inplace=True); ##permanent reset

In [27]:
df

    StudentID    Name Department   Age  Marks  Attendance       City
0           1    Amit         CS  20.0   85.0        92.0  Ahmedabad
1           2    Neha         IT  21.0   78.0        88.0      Surat
2           3    Ravi         CS  19.0   90.0        95.0  Ahmedabad
3           4    Sara         EC  22.0   66.0        70.0   Vadodara
4           5    John         IT  20.0  120.0        85.0     Rajkot
5           6   Kiran         CS  21.0   81.0        90.0  Ahmedabad
6           7    Riya         IT  20.0   76.0         NaN      Surat
7           8   Arjun         CS  22.0    NaN        93.0  Ahmedabad
8           9   Pooja         EC  19.0   69.0        75.0   Vadodara
9          10   Mehul         CS  21.0   92.0        97.0  Ahmedabad
10         11   Anita         IT  20.0   74.0        80.0      Surat
11         12   Rohan         CS  22.0   84.0        91.0  Ahmedabad
12         13   Deepa         EC   NaN   67.0        72.0   Vadodara
13         14   Sneha         IT  20.0   79.0        86.0      Surat
14         15   Kunal         CS  23.0   91.0        96.0  Ahmedabad
15         16   Payal         EC  19.0   65.0        68.0   Vadodara
16         17  Nikhil         IT  22.0   83.0        89.0      Surat
17         18  Simran         CS  21.0   87.0        94.0  Ahmedabad
18         19   Tarun         CS  20.0   77.0        84.0     Rajkot
19         20    Isha         IT   NaN   30.0        87.0      Surat
20          2    Neha         IT  21.0   78.0        88.0      Surat
21          6   Kiran         CS  21.0   81.0        90.0  Ahmedabad

## DataFrame Attribute

In [29]:
print(df.shape)
print(df.size)
print(df.ndim)
print(df.columns)
print(df.index)
print(df.dtypes)
print(df.values)

(22, 7)
154
2
Index(['StudentID', 'Name', 'Department', 'Age', 'Marks', 'Attendance',
       'City'],
      dtype='object')
RangeIndex(start=0, stop=22, step=1)
StudentID       int64
Name           object
Department     object
Age           float64
Marks         float64
Attendance    float64
City           object
dtype: object
[[1 'Amit' 'CS' 20.0 85.0 92.0 'Ahmedabad']
 [2 'Neha' 'IT' 21.0 78.0 88.0 'Surat']
 [3 'Ravi' 'CS' 19.0 90.0 95.0 'Ahmedabad']
 [4 'Sara' 'EC' 22.0 66.0 70.0 'Vadodara']
 [5 'John' 'IT' 20.0 120.0 85.0 'Rajkot']
 [6 'Kiran' 'CS' 21.0 81.0 90.0 'Ahmedabad']
 [7 'Riya' 'IT' 20.0 76.0 nan 'Surat']
 [8 'Arjun' 'CS' 22.0 nan 93.0 'Ahmedabad']
 [9 'Pooja' 'EC' 19.0 69.0 75.0 'Vadodara']
 [10 'Mehul' 'CS' 21.0 92.0 97.0 'Ahmedabad']
 [11 'Anita' 'IT' 20.0 74.0 80.0 'Surat']
 [12 'Rohan' 'CS' 22.0 84.0 91.0 'Ahmedabad']
 [13 'Deepa' 'EC' nan 67.0 72.0 'Vadodara']
 [14 'Sneha' 'IT' 20.0 79.0 86.0 'Surat']
 [15 'Kunal' 'CS' 23.0 91.0 96.0 'Ahmedabad']
 [16 'Payal' 'EC' 19.0 65.0 68.0 'Vadodara']
 [17 'Nikhil' 'IT' 22.0 83.0 89.0 'Surat']
 [18 'Simran' 'CS' 21.0 87.0 94.0 'Ahmedabad']
 [19 'Tarun' 'CS' 20.0 77.0 84.0 'Rajkot']
 [20 'Isha' 'IT' nan 30.0 87.0 'Surat']
 [2 'Neha' 'IT' 21.0 78.0 88.0 'Surat']
 [6 'Kiran' 'CS' 21.0 81.0 90.0 'Ahmedabad']]

In [32]:
data={
    "Name":['a','b','c','d','e'],
    "marks":[85,90,95,70,np.nan],
    "city":["ahem","raj","Jam","BOB","Lim"],
    "bonus":[9,1,4,5,6]
}
df=pd.DataFrame(data)
df

  Name  marks  city  bonus
0    a   85.0  ahem      9
1    b   90.0   raj      1
2    c   95.0   Jam      4
3    d   70.0   BOB      5
4    e    NaN   Lim      6

## Loc method
- label based method for slicing and indexing

### Slicing

In [35]:
df.loc[0,"marks"]

85.0

In [38]:
df.loc[0:2,['Name','city']]

  Name  city
0    a  ahem
1    b   raj
2    c   Jam

## Add colums

In [39]:
df.loc[:,"total"]=df["marks"]+df["bonus"]

In [40]:
df

  Name  marks  city  bonus  total
0    a   85.0  ahem      9   94.0
1    b   90.0   raj      1   91.0
2    c   95.0   Jam      4   99.0
3    d   70.0   BOB      5   75.0
4    e    NaN   Lim      6    NaN

## add row

In [43]:
df.loc[5]=['F',90,"Cal",2,92]

In [44]:
df

  Name  marks  city  bonus  total
0    a   85.0  ahem      9   94.0
1    b   90.0   raj      1   91.0
2    c   95.0   Jam      4   99.0
3    d   70.0   BOB      5   75.0
4    e    NaN   Lim      6    NaN
5    F   90.0   Cal      2   92.0

In [45]:
df.loc[5]

Name       F
marks     90
city     Cal
bonus      2
total     92
Name: 5, dtype: object

## iloc method

In [46]:
df.iloc[0:2]  ## here last index(i.e 2) is not included unlike loc

  Name  marks  city  bonus  total
0    a   85.0  ahem      9   94.0
1    b   90.0   raj      1   91.0

In [47]:
df.iloc[0:2,"city"]

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [50]:
df.iloc[0:2,2]

0    ahem
1     raj
Name: city, dtype: object

In [49]:
df

  Name  marks  city  bonus  total
0    a   85.0  ahem      9   94.0
1    b   90.0   raj      1   91.0
2    c   95.0   Jam      4   99.0
3    d   70.0   BOB      5   75.0
4    e    NaN   Lim      6    NaN
5    F   90.0   Cal      2   92.0

In [51]:
df.iloc[2]

Name       c
marks     95
city     Jam
bonus      4
total     99
Name: 2, dtype: object

In [52]:
df.loc[2]

Name       c
marks     95
city     Jam
bonus      4
total     99
Name: 2, dtype: object

In [ ]:
df

## head()

In [53]:
df.head() ## first 5

  Name  marks  city  bonus  total
0    a   85.0  ahem      9   94.0
1    b   90.0   raj      1   91.0
2    c   95.0   Jam      4   99.0
3    d   70.0   BOB      5   75.0
4    e    NaN   Lim      6    NaN

In [54]:
df.tail() ## Last 5

  Name  marks city  bonus  total
1    b   90.0  raj      1   91.0
2    c   95.0  Jam      4   99.0
3    d   70.0  BOB      5   75.0
4    e    NaN  Lim      6    NaN
5    F   90.0  Cal      2   92.0

## Sample()

In [55]:
df.sample(2)

  Name  marks  city  bonus  total
3    d   70.0   BOB      5   75.0
0    a   85.0  ahem      9   94.0

In [56]:
df.sample(2) ## Random 2

  Name  marks city  bonus  total
2    c   95.0  Jam      4   99.0
4    e    NaN  Lim      6    NaN

In [57]:
df.sample(3)

  Name  marks  city  bonus  total
3    d   70.0   BOB      5   75.0
4    e    NaN   Lim      6    NaN
0    a   85.0  ahem      9   94.0

## inspect data

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   marks   5 non-null      float64
 2   city    6 non-null      object
 3   bonus   6 non-null      int64
 4   total   5 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 448.0+ bytes

In [60]:
df

  Name  marks  city  bonus  total
0    a   85.0  ahem      9   94.0
1    b   90.0   raj      1   91.0
2    c   95.0   Jam      4   99.0
3    d   70.0   BOB      5   75.0
4    e    NaN   Lim      6    NaN
5    F   90.0   Cal      2   92.0

In [61]:
df.info

<bound method DataFrame.info of   Name  marks  city  bonus  total
0    a   85.0  ahem      9   94.0
1    b   90.0   raj      1   91.0
2    c   95.0   Jam      4   99.0
3    d   70.0   BOB      5   75.0
4    e    NaN   Lim      6    NaN
5    F   90.0   Cal      2   92.0>

### Describe method
- Statistical summary
 **Syntax**

In [65]:
df.describe()

           marks     bonus      total
count   5.000000  6.000000   5.000000
mean   86.000000  4.500000  90.200000
std     9.617692  2.880972   9.038805
min    70.000000  1.000000  75.000000
25%    85.000000  2.500000  91.000000
50%    90.000000  4.500000  92.000000
75%    90.000000  5.750000  94.000000
max    95.000000  9.000000  99.000000

In [66]:
df.describe(include='all')

       Name      marks city     bonus      total
count     6   5.000000    6  6.000000   5.000000
unique    6        NaN    6       NaN        NaN
top       a        NaN  BOB       NaN        NaN
freq      1        NaN    1       NaN        NaN
mean    NaN  86.000000  NaN  4.500000  90.200000
std     NaN   9.617692  NaN  2.880972   9.038805
min     NaN  70.000000  NaN  1.000000  75.000000
25%     NaN  85.000000  NaN  2.500000  91.000000
50%     NaN  90.000000  NaN  4.500000  92.000000
75%     NaN  90.000000  NaN  5.750000  94.000000
max     NaN  95.000000  NaN  9.000000  99.000000

In [67]:
df.describe(exclude='object').round(2) ## name and city are object so excluded

       marks  bonus  total
count   5.00   6.00   5.00
mean   86.00   4.50  90.20
std     9.62   2.88   9.04
min    70.00   1.00  75.00
25%    85.00   2.50  91.00
50%    90.00   4.50  92.00
75%    90.00   5.75  94.00
max    95.00   9.00  99.00

In [70]:
df.describe(percentiles=[.20,.30,.45,.87]).round(2)

       marks  bonus  total
count   5.00   6.00   5.00
mean   86.00   4.50  90.20
std     9.62   2.88   9.04
min    70.00   1.00  75.00
20%    82.00   2.00  87.80
30%    86.00   3.00  91.20
45%    89.00   4.25  91.80
50%    90.00   4.50  92.00
87%    92.40   7.05  96.40
max    95.00   9.00  99.00

In [71]:
mystats=df.describe(percentiles=[.20,.30,.45,.87]).round(2)
print(mystats)

       marks  bonus  total
count   5.00   6.00   5.00
mean   86.00   4.50  90.20
std     9.62   2.88   9.04
min    70.00   1.00  75.00
20%    82.00   2.00  87.80
30%    86.00   3.00  91.20
45%    89.00   4.25  91.80
50%    90.00   4.50  92.00
87%    92.40   7.05  96.40
max    95.00   9.00  99.00

In [72]:
mystats['marks']

count     5.00
mean     86.00
std       9.62
min      70.00
20%      82.00
30%      86.00
45%      89.00
50%      90.00
87%      92.40
max      95.00
Name: marks, dtype: float64

## Unique and nunique methods

In [73]:
df['city'].unique() ## gives unique city

array(['ahem', 'raj', 'Jam', 'BOB', 'Lim', 'Cal'], dtype=object)

In [74]:
df['city'].nunique() ## gives no of unique city

6

In [75]:
df

  Name  marks  city  bonus  total
0    a   85.0  ahem      9   94.0
1    b   90.0   raj      1   91.0
2    c   95.0   Jam      4   99.0
3    d   70.0   BOB      5   75.0
4    e    NaN   Lim      6    NaN
5    F   90.0   Cal      2   92.0

## Value count
- Counts the frequency

In [76]:
df['city'].value_counts()

BOB     1
ahem    1
raj     1
Jam     1
Cal     1
Lim     1
Name: city, dtype: int64

In [77]:
df['city'].value_counts(ascending=True)

Lim     1
Cal     1
Jam     1
raj     1
ahem    1
BOB     1
Name: city, dtype: int64